// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL5Bg9p6uXhqzF0TplhStdD0MpG3KHoLE',
    appId: '1:560790954993:web:dcb97ff0a9347d96939a50',
    messagingSenderId: '560790954993',
    projectId: 'twelve-future-and-stream',
    authDomain: 'twelve-future-and-stream.firebaseapp.com',
    storageBucket: 'twelve-future-and-stream.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM_VwykeY63lZrrc6NOi4IQKxBNnXmTKo',
    appId: '1:560790954993:android:0160cf0ff91d36a7939a50',
    messagingSenderId: '560790954993',
    projectId: 'twelve-future-and-stream',
    storageBucket: 'twelve-future-and-stream.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBueq4QuSoShwkNErNU_2h93PUpBRVxJdY',
    appId: '1:560790954993:ios:2dfdf09772057b12939a50',
    messagingSenderId: '560790954993',
    projectId: 'twelve-future-and-stream',
    storageBucket: 'twelve-future-and-stream.firebasestorage.app',
    iosBundleId: 'com.sohail.twelveFutureAndStream',
  );
}
